version: "3"
services:
  cabbage:
    depends_on:
      postgres_db:
        condition: service_healthy
    build:
      context: .
      dockerfile: Dockerfile 
    image: cabbage:0.2.0
    env_file:
      - ".env"
    networks:
      - cabbage
    working_dir: /usr/src/cabbage
    ports:
      - "5000:5000"
    command: bash -c "bash migrate.sh && bash run.sh"
  postgres_db:
    image: postgres:latest
    command: -p 5434
    env_file:
      - ".env"
    expose:
      - 5434
    ports:
      - "5434:5434"
    networks:
      - cabbage
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d postgres -U postgres -p 5434" ] 
      interval: 5s
      timeout: 20s
      retries: 3
networks:
  cabbage:
      driver: bridge