apiVersion: v1
kind: PersistentVolume
metadata:
  name: cabbage-pvc
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /usr/src/cabbage
