apiVersion: v1
kind: ReplicationController
metadata:
  name: celery
spec:
  replicas: 1
  template:
    metadata:
      name: celery
      labels:
        io.kompose.network/cabbage: "true"
        app: celery
    spec:
      containers:
        - name: celery
          image: docker-nexus.c-atmosphere.duckdns.org/cabbage:0.4.1
          imagePullPolicy: IfNotPresent
          command: ["/opt/env/bin/celery"]
          args: ["-A", "core", "worker" ,"-l", "INFO"]
          env:
            - name: ALLOWED_HOSTS
              valueFrom:
                configMapKeyRef:
                  key: ALLOWED_HOSTS
                  name: env
            - name: APPEND_SLASH
              valueFrom:
                configMapKeyRef:
                  key: APPEND_SLASH
                  name: env
            - name: DEBUG
              valueFrom:
                configMapKeyRef:
                  key: DEBUG
                  name: env
            - name: DJANGO_SUPERUSER_EMAIL
              valueFrom:
                configMapKeyRef:
                  key: DJANGO_SUPERUSER_EMAIL
                  name: env
            - name: DJANGO_SUPERUSER_FULL_NAME
              valueFrom:
                configMapKeyRef:
                  key: DJANGO_SUPERUSER_FULL_NAME
                  name: env
            - name: DJANGO_SUPERUSER_PASSWORD
              valueFrom:
                configMapKeyRef:
                  key: DJANGO_SUPERUSER_PASSWORD
                  name: env
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  key: POSTGRES_DB
                  name: env
            - name: POSTGRES_HOST
              valueFrom:
                configMapKeyRef:
                  key: POSTGRES_HOST
                  name: env
            - name: POSTGRES_PASSWORD
              valueFrom:
                configMapKeyRef:
                  key: POSTGRES_PASSWORD
                  name: env
            - name: POSTGRES_PORT
              valueFrom:
                configMapKeyRef:
                  key: POSTGRES_PORT
                  name: env
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  key: POSTGRES_USER
                  name: env
            - name: CELERY_BROKER_URL
              valueFrom:
                configMapKeyRef:
                  key: CELERY_BROKER_URL
                  name: env
            - name: SECRET_KEY
              valueFrom:
                configMapKeyRef:
                  key: SECRET_KEY
                  name: env
          ports:
            - containerPort: 5000
          resources:
            requests:
              cpu: 200m
              memory: 256Mi
            limits:
              cpu: 300m
              memory: 512Mi
          workingDir: /usr/src/cabbage
