# Generated by Django 2.1 on 2018-08-19 22:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='Adresse Mail')),
                ('full_name', models.CharField(max_length=255, verbose_name='Nom et Prénom')),
                ('babysitter', models.BooleanField(default=False, verbose_name='Compte Babysitter')),
                ('active_profile', models.BooleanField(default=True, verbose_name='Actif')),
                ('staff_profile', models.BooleanField(default=False, verbose_name='Staff')),
                ('admin_profile', models.BooleanField(default=False, verbose_name='Administrateur')),
                ('creation_date', models.DateField(default=django.utils.timezone.now, verbose_name='Date de création')),
            ],
            options={
                'verbose_name': 'Membre',
                'verbose_name_plural': 'Membres',
            },
        ),
    ]
