# Generated by Django 2.0.6 on 2018-07-08 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BabySitter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nurse_name', models.CharField(max_length=42)),
                ('age', models.PositiveSmallIntegerField()),
                ('ville', models.CharField(max_length=64)),
                ('job', models.CharField(choices=[('MF', 'Mère au Foyer')], default='MF', max_length=2)),
                ('age_target', models.CharField(choices=[('BBY', 'Nouveau né (0 à 10 mois)'), ('GBA', 'Nourrisson (10 mois à 2 ans)'), ('CHI', 'Enfants de 2 à 6 ans'), ('GCH', 'Enfants de 7 à 12 ans'), ('TEE', 'Enfants de 12 ans et plus')], default='BBY', max_length=2)),
            ],
        ),
    ]
