# Generated by Django 2.0.6 on 2018-07-10 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('babysittersList', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='babysitter',
            name='time_target',
            field=models.CharField(choices=[('AM', 'Matin'), ('PM', 'Après-midi'), ('DAY', 'Toute la journée'), ('EV', 'Toute la soirée')], default='AM', max_length=4),
        ),
        migrations.AlterField(
            model_name='babysitter',
            name='age_target',
            field=models.CharField(choices=[('BBY', 'Nouveau né (0 à 10 mois)'), ('GBA', 'Nourrisson (10 mois à 2 ans)'), ('CHI', 'Enfants de 2 à 6 ans'), ('GCH', 'Enfants de 7 à 12 ans'), ('TEE', 'Enfants de 12 ans et plus')], default='BBY', max_length=4),
        ),
    ]
