# Generated by Django 2.0.6 on 2018-07-10 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('babysittersList', '0002_auto_20180710_1913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='babysitter',
            name='time_target',
            field=models.CharField(choices=[('BLANK', ' '), ('AM', 'Matin'), ('PM', 'Après-midi'), ('DAY', 'Toute la journée'), ('EV', 'Toute la soirée')], default='BLANK', max_length=4),
        ),
    ]
