# Generated by Django 2.0.6 on 2018-07-10 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('babysittersList', '0003_auto_20180710_1943'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='babysitter',
            name='age_target',
        ),
        migrations.RemoveField(
            model_name='babysitter',
            name='job',
        ),
        migrations.RemoveField(
            model_name='babysitter',
            name='name',
        ),
        migrations.RemoveField(
            model_name='babysitter',
            name='time_target',
        ),
        migrations.RemoveField(
            model_name='babysitter',
            name='ville',
        ),
        migrations.AddField(
            model_name='babysitter',
            name='Deuxième diplôme (si vous en avez un) ',
            field=models.CharField(choices=[('BLANK', ' '), ('BAF', 'BAFA'), ('DPE', 'Diplôme de petite enfance')], default='BLANK', max_length=4),
        ),
        migrations.AddField(
            model_name='babysitter',
            name='Moments de la journée ',
            field=models.CharField(choices=[('BLANK', ' '), ('AM', 'Matin'), ('PM', 'Après-midi'), ('DAY', 'Toute la journée'), ('EV', 'Toute la soirée')], default='BLANK', max_length=4),
        ),
        migrations.AddField(
            model_name='babysitter',
            name='Premier diplôme (si vous en avez un) ',
            field=models.CharField(choices=[('BLANK', ' '), ('BAF', 'BAFA'), ('DPE', 'Diplôme de petite enfance')], default='BLANK', max_length=4),
        ),
        migrations.AddField(
            model_name='babysitter',
            name="Tranche d'âge de l'enfant ",
            field=models.CharField(choices=[('BLANK', ' '), ('BBY', 'Nouveau né (0 à 10 mois)'), ('GBA', 'Nourrisson (10 mois à 2 ans)'), ('CHI', 'Enfants de 2 à 6 ans'), ('GCH', 'Enfants de 7 à 12 ans'), ('TEE', 'Enfants de 12 ans et plus')], default='BLANK', max_length=4),
        ),
        migrations.AddField(
            model_name='babysitter',
            name='Troisième diplôme (si vous en avez un) ',
            field=models.CharField(choices=[('BLANK', ' '), ('BAF', 'BAFA'), ('DPE', 'Diplôme de petite enfance')], default='BLANK', max_length=4),
        ),
        migrations.AddField(
            model_name='babysitter',
            name='Votre lieu de résidence ',
            field=models.CharField(default=' ', max_length=64),
        ),
        migrations.AddField(
            model_name='babysitter',
            name='Votre nom ',
            field=models.CharField(default=' ', max_length=42),
        ),
        migrations.AddField(
            model_name='babysitter',
            name='Votre profession ou situation actuelle ',
            field=models.CharField(choices=[('BLANK', ' '), ('MF', 'Mère au Foyer')], default='BLANK', max_length=4),
        ),
        migrations.AddField(
            model_name='babysitter',
            name='aid_certificate_grade',
            field=models.BooleanField(default=False, verbose_name="Vous êtes titulaire d'un brevet de secourisme ?"),
        ),
        migrations.AddField(
            model_name='babysitter',
            name='criminal_record',
            field=models.BooleanField(default=False, verbose_name="J'atteste sur l'honneur et déclare avoir un casier judiciaire (B1 et B2) vierge.\n(Notez toutefois que la famille de l'enfant peut demander une copie de vos deux casiers judiciaires.)"),
        ),
        migrations.AddField(
            model_name='babysitter',
            name='price',
            field=models.IntegerField(default=0, verbose_name='Tarifs de vos prestations'),
        ),
        migrations.AddField(
            model_name='babysitter',
            name='price_unit',
            field=models.CharField(choices=[('H', 'Heure'), ('DM', 'Demi-Journée'), ('DAY', 'Jour'), ('WEE', 'Semaine')], default='H', max_length=4, verbose_name='par '),
        ),
        migrations.AlterField(
            model_name='babysitter',
            name='age',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Votre âge '),
        ),
    ]
