# Generated by Django 2.0.7 on 2018-07-12 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('babysittersList', '0007_auto_20180712_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='babysitter',
            name='grade_main',
            field=models.CharField(choices=[('BLANK', ' '), ('BAF', 'BAFA'), ('DPE', 'Diplôme de petite enfance')], default='BLANK', max_length=4, null=True, verbose_name='Premier diplôme (Si vous en disposez)'),
        ),
        migrations.AlterField(
            model_name='babysitter',
            name='grade_sec',
            field=models.CharField(choices=[('BLANK', ' '), ('BAF', 'BAFA'), ('DPE', 'Diplôme de petite enfance')], default='BLANK', max_length=4, null=True, verbose_name='2ème diplôme (Si vous en disposez)'),
        ),
        migrations.AlterField(
            model_name='babysitter',
            name='grade_tri',
            field=models.CharField(choices=[('BLANK', ' '), ('BAF', 'BAFA'), ('DPE', 'Diplôme de petite enfance')], default='BLANK', max_length=4, null=True, verbose_name='3ème diplôme (Si vous en disposez)'),
        ),
    ]
