# Generated by Django 2.0.7 on 2018-07-12 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('babysittersList', '0009_auto_20180712_1755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='babysitter',
            name='grade_main',
            field=models.CharField(blank=True, choices=[('BLANK', ' '), ('BAF', 'BAFA'), ('DPE', 'Diplôme de petite enfance')], max_length=4, verbose_name='Premier diplôme (Si vous en disposez)'),
        ),
    ]
