# Generated by Django 2.0.7 on 2018-07-16 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('babysittersList', '0012_auto_20180716_1318'),
        ('babysittersList', '0012_auto_20180716_1732'),
    ]

    operations = [
    ]
