# Generated by Django 2.0.7 on 2018-07-16 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('babysittersList', '0014_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='babysitter_ptr',
        ),
        migrations.RenameField(
            model_name='babysitter',
            old_name='nurse_name',
            new_name='name',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
