# Generated by Django 2.0.7 on 2018-07-16 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('babysittersList', '0016_auto_20180716_2100'),
    ]

    operations = [
        migrations.RenameField(
            model_name='babysitter',
            old_name='user_link',
            new_name='user',
        ),
    ]
