# Generated by Django 2.0.7 on 2018-07-16 20:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('babysittersList', '0017_auto_20180716_2106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='babysitter',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='babysittersList.User'),
        ),
    ]
