# Generated by Django 2.0.7 on 2018-07-17 11:01

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('babysittersList', '0019_user_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(default=' ', max_length=128, verbose_name='Numéro de téléphone'),
        ),
    ]
