# Generated by Django 2.0.7 on 2018-07-17 11:02

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('babysittersList', '0020_auto_20180717_1301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, verbose_name='Numéro de téléphone'),
        ),
    ]
