# Generated by Django 2.0.7 on 2018-07-17 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('babysittersList', '0021_auto_20180717_1302'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(default=' ', max_length=254, verbose_name='Adresse électronique'),
        ),
    ]
