# Generated by Django 2.0.7 on 2018-07-17 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('babysittersList', '0022_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='job',
            field=models.CharField(blank=True, choices=[('CAD', 'Cadre'), ('CAS', 'Cadre Supérieur'), ('CAP', 'Cadre de la fonction publique'), ('AGP', 'Agent de production'), ('ENS', 'Enseignant'), ('MF', 'Mère au Foyer')], max_length=4, verbose_name='Profession'),
        ),
    ]
