# Generated by Django 2.0.7 on 2018-07-17 16:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('babysittersList', '0024_user_creation_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='birth',
            field=models.DateField(default=django.utils.timezone.now, max_length=8),
        ),
    ]
