# Generated by Django 2.0.7 on 2018-07-17 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('babysittersList', '0026_babysitter_linkedin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birth_location',
            field=models.CharField(blank=True, max_length=64, verbose_name='Lieu de naissance'),
        ),
    ]
