# Generated by Django 2.0.7 on 2018-07-17 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('babysittersList', '0027_auto_20180717_1944'),
    ]

    operations = [
        migrations.AddField(
            model_name='babysitter',
            name='location',
            field=models.CharField(blank=True, choices=[('AIX', 'Aix-en-Provence'), ('MAR', 'Marseille'), ('AVG', 'Avignon')], max_length=4, verbose_name='Ville et environs'),
        ),
        migrations.AlterField(
            model_name='user',
            name='job',
            field=models.CharField(blank=True, choices=[('CAD', 'Cadre'), ('CAS', 'Cadre Supérieur'), ('CAP', 'Cadre de la fonction publique'), ('AGP', 'Agent de production'), ('ENS', 'Enseignant'), ('MFO', 'Mère au Foyer'), ('RET', 'Retraitée')], max_length=4, verbose_name='Profession'),
        ),
    ]
