# Generated by Django 2.0.7 on 2018-07-18 07:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('babysittersList', '0028_auto_20180717_1954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birth',
            field=models.DateField(default=django.utils.timezone.now, max_length=8, verbose_name='Date de naissance'),
        ),
    ]
