# Generated by Django 2.0.7 on 2018-07-18 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('babysittersList', '0029_auto_20180718_0937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(default=' ', max_length=60, verbose_name='Nom'),
        ),
    ]
