# Generated by Django 2.2.2 on 2019-06-14 01:42

from django.db import migrations
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('babysitters', '0003_auto_20180824_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='babysitter',
            name='price',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default_currency='EUR', max_digits=10, verbose_name='Tarifs de vos prestations'),
        ),
    ]
