# Generated by Django 2.2.2 on 2019-06-19 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('babysitters', '0005_auto_20190619_0900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='babysitter',
            name='location',
            field=models.CharField(blank=True, choices=[('AIX', 'Aix-en-Provence'), ('MAR', 'Marseille'), ('AVG', 'Avignon')], max_length=4, verbose_name='Ville et environs'),
        ),
    ]
