# Generated by Django 2.2.2 on 2019-06-19 15:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('babysitters', '0007_auto_20190619_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='babysitter',
            name='accounts',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
