# Generated by Django 2.1 on 2018-08-24 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('babysitters', '0002_auto_20180821_1946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='babysitter',
            name='location',
            field=models.CharField(choices=[('AIX', 'Aix-en-Provence'), ('MAR', 'Marseille'), ('AVG', 'Avignon')], max_length=4, verbose_name='Ville et environs'),
        ),
    ]
