# Generated by Django 2.2.2 on 2019-06-15 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_member_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='username',
        ),
        migrations.AlterField(
            model_name='member',
            name='full_name',
            field=models.CharField(max_length=255, verbose_name='Prénom et NOM'),
        ),
    ]
