# Generated by Django 2.2.2 on 2019-06-19 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_member_active_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='admin_profile',
        ),
        migrations.RemoveField(
            model_name='member',
            name='staff_profile',
        ),
    ]
