# Generated by Django 2.2.2 on 2019-06-19 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20190619_0825'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounts',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Actif'),
        ),
        migrations.AddField(
            model_name='accounts',
            name='is_admin',
            field=models.BooleanField(default=False, verbose_name='Administrateur'),
        ),
        migrations.AddField(
            model_name='accounts',
            name='is_staff',
            field=models.BooleanField(default=False, verbose_name='Staff'),
        ),
    ]
