# Generated by Django 2.2.2 on 2019-06-19 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20190619_0832'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accounts',
            old_name='is_admin',
            new_name='admin_profile',
        ),
        migrations.RenameField(
            model_name='accounts',
            old_name='is_staff',
            new_name='staff_profile',
        ),
    ]
