# Generated by Django 2.2.2 on 2019-06-19 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20190619_0840'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='staff_profile',
            new_name='is_staff',
        ),
    ]
